name: project2
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish to pub.dev

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  connectivity_plus: ^2.3.0
  email_validator: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
